server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/mybatis
    password: 666888
    username: root
#    testOnBorrow: true
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: SELECT 1
#    max-active: 15
#    max-idle: 10
#    max-wait: 8000

 # 多个数据源配置
  #datasource:
    dbproductservice:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      password: 666888
      username: root
      testOnBorrow: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      max-active: 15
      max-idle: 10
      max-wait: 8000
    dbuserservice:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/exe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      password: 666888
      username: root
      testOnBorrow: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      max-active: 15
      max-idle: 10
      max-wait: 8000


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dfec.springbootmybatis.entity
  #开启MyBatis的二级缓存
  configuration:
    cache-enabled: false

#showSql
#logging:
#  file:
#    path: main\resources\log\mylog.log
#  level:
#    root: WARN