server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080

spring:
  application:
    name: redis
  resources:
    static-locations: classpath:/resources/,file:/usr/local/soft/service/,file:H:/workspace-photon/service/
  profiles:
    active: dev
  swagger:
    enabled: true
    title: API
    base-package: com
    description: API文档
    version: 1.0.0
    contact:
      name: Andy
      email: 646959428@qq.com
      url: http://www.dfec.com.cn
    security:
      # 是否启用 swagger 登录验证
      filter-plugin: true
      username: admin
      password: admin@123
    global-operation-parameters[0]:
      description: 'token,必填项'
      modelRef: 'string'
      name: 'token'
      parameter-type: 'header'
      required: true





